### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by sindresorhus** [avajs/caching-transform#5]
There are a bunch of changes here now, so I think it's time for a new major release. I've updated all the dependencies except for one.

TODO

- [x] There's a failing test that was failing in master too before I did anything: https://github.com/avajs/caching-transform/blob/50cc9935bad0465bc1da6505e25576b59477a14e/test.js#L376
- [x] `mock-fs` needs to be upgraded, but not exactly sure what needs changing.

@novemberborn Since you have more insight into the codebase, could you help out with the remaining items and do a new release?

**Comment by novemberborn** [comment]
@sindresorhus are you looking to use this in another project?

Right now AVA and nyc seem to be the only consumers of this library. nyc still targets Node.js 0.10 so won't be able to upgrade.

**Comment by sindresorhus** [comment]
No, just doing some maintenance work, upgrading some dependencies, so they can be deduped better.

> nyc still targets Node.js 0.10 so won't be able to upgrade.

Does that really matter? The published version is 1.5 years old, so I doubt new issues will come in. They can just stay at the existing version until they upgrade.

**Comment by novemberborn** [comment]
Fair enough. I'll try and do the AVA upgrade and get this repo in a good state too.



>> nyc still targets Node.js 0.10 so won't be able to upgrade.
>
> Does that really matter? The published version is 1.5 years old, so I doubt new issues will come in. They can just stay at the existing version until they upgrade.

No, I think I meant to say that we don't need to worry about upgrading it / testing the new version with nyc.

**Comment by coreyfarrell** [comment]
FWIW nyc does not work on node 0.10 or 0.12.  I'm unsure if it's possible to get it working with babel but nyc and dependencies (find-up at minimum) produce the error `SyntaxError: Use of const in strict mode` under 0.10 and 0.12.  Verified this failure by running: `npm install --prod && ./bin/nyc.js ./bin/nyc.js --help`.  In my local system (node 8) this prints the nyc CLI help followed by the coverage report.

**Comment by novemberborn** [comment]
We're removing this package from AVA. I'll reach out and see if Istanbul wants to maintain it instead.

**Comment by sindresorhus** [comment]
A new release is out. We'll still looking for someone to maintain it as it doesn't make sense to have it in this org when we don't use it ourselves.

**Comment by JaKXz** [comment]
@sindresorhus @coreyfarrell 👋 I could volunteer to maintain this repo inside the `istanbuljs` org since `nyc` does use this heavily :)
